name: UI Tests

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  ui_test:
    name: Run android UI test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.2'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: run tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew :app:connectedFullDebugAndroidTest --no-daemon --no-parallel

      - name: pull test video recordings
        run: |
          mkdir -p /test_recordings
          adb -e pull /sdcard/test_recordings /test_recordings

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-recordings
          path: test_recordings
